# Check the length of lines in the source code
Layout/LineLength:
  Enabled: false

# Disable all Metrics related cops
Metrics:
  Enabled: false

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: false

# Add the frozen_string_literal comment to the top of files to help transition from Ruby 2.3.0 to Ruby 3.0.
Style/FrozenStringLiteralComment:
  Enabled: false
